# Generated by Django 2.2.4 on 2019-10-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=100)),
                ('opportunity_type', models.CharField(max_length=100)),
                ('lead_source', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('close_date', models.CharField(max_length=20)),
                ('opportunity_status', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
